name: build_gpuhoomd3conda

on:
  push:
    branches: [ main ]
    # Run when container is changed
    paths:
        - 'containers/dockerfile_gpuhoomd3conda'

jobs:
  build_gpuhoomdconda:
    if: github.repository_owner == 'cmelab'
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./containers/dockerfile_gpuhoomd3conda
          push: true
          tags: cmelab/gpuhoomd3conda:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
