name: build_gpuhoomd3conda

on:
  push:
    branches: ['main']
    # Run when container is changed
    paths:
        - 'containers/dockerfile_gpuhoomd3conda'
  # Allows workflow to be manually triggered
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gpuhoomd3conda

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action
        with:
          context: .
          file: ./containers/dockerfile_gpuhoomd3conda
          push: true
          tags: ${{ env.REGISTRY }}/cmelab/${{ env.IMAGE_NAME }}:latest
